# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'donbealbum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for donbealbum
  pod 'Masonry', '~> 1.1.0'
  pod 'FMDB', '~> 2.7.5'

  target 'donbealbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'donbealbumUITests' do
    # Pods for testing
  end

end
